# Generated by Django 4.0 on 2021-12-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('status', models.CharField(choices=[('STATUS', 'Status'), ('INACTIVE', 'Inactive')], default='active', max_length=100)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=100)),
                ('practice', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('reporting_managers', models.CharField(max_length=100)),
                ('practice_lead', models.CharField(max_length=100)),
                ('data_of_joining', models.DateField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('mt_experience', models.FloatField(max_length=100)),
                ('non_mt_experience', models.FloatField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='active', max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'EmployeeDetails',
            },
        ),
    ]
