# Generated by Django 4.0 on 2021-12-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='data_of_joining',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
