# Generated by Django 4.0 on 2021-12-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_employeedetails_data_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='active', max_length=100),
        ),
    ]
