# Generated by Django 4.0 on 2021-12-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_employeedetails_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='s_no',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
