# Generated by Django 4.0 on 2021-12-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_employeedetails_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='s_no',
            field=models.IntegerField(null=True),
        ),
    ]
