# Generated by Django 4.0 on 2022-01-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_employeedetails_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='department',
            field=models.CharField(blank=True, choices=[('DEVOPS', 'DevOps'), ('ENTERPRISE APPLICATION DEVELOPMENT', 'Enterprise Application Development'), ('ui', 'UI'), ('CLOUD SOLUTIONS', 'Could Solutions'), ('ENTERPRISE ARCHITECTURE', 'Enterprise Architecture'), ('ux', 'UX'), ('PRODUCT ENGINEERING', 'Product Engineering'), ('MOBILITY', 'Mobility'), ('PROFESSIONAL SERVICES', 'Professional Services')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='practice',
            field=models.CharField(blank=True, choices=[('DIGITAL TRANSFORMATION', 'Digital Transformation')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='practice_lead',
            field=models.CharField(blank=True, choices=[('SURESH TUKARAM SUTAR', 'Suresh Tukaram SUTAR'), ('SAILAJA GUDALA', 'Sailaja GUDALA'), ('SRINIVAS KATTUNGA', 'Srinivas KATTUNGA'), ('ABHIJEET BHIKAJI PATIL', 'Abhijeet Bhikaji PATIL'), ('SANJAY PARMANAND BATHEJA', 'Sanjay Parmanand BATHEJA'), ('VYOMA DILIP PATHAK', 'Vyoma Dilip PATHAK'), ('ABHIJEET HARICHANDRA ALONE', 'Abhijeet Harishchandra ALONE'), ('NASIR AHMED R', 'Nasir Ahmed R')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RESIGN', 'Resign')], default='Active', max_length=100, null=True),
        ),
    ]
