# Generated by Django 4.0 on 2022-01-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_employeedetails_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='department',
            field=models.CharField(choices=[('DEVOPS', 'DevOps'), ('ENTERPRISE APPLICATION DEVELOPMENT', 'Enterprise Application Development'), ('UI', 'UI'), ('CLOUD SOLUTIONS', 'Cloud Solutions'), ('ENTERPRISE ARCHITECTURE', 'Enterprise Architecture'), ('UX', 'UX'), ('PRODUCT ENGINEERING', 'Product Engineering'), ('MOBILITY', 'Mobility'), ('PROFESSIONAL SERVICES', 'Professional Services')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='mt_experience',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='practice',
            field=models.CharField(choices=[('DIGITAL TRANSFORMATION', 'Digital Transformation')], default='Digital Transformation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='practice_lead',
            field=models.CharField(choices=[('SURESH TUKARAM SUTAR', 'Suresh Tukaram SUTAR'), ('SAILAJA GUDALA', 'Sailaja GUDALA'), ('SRINIVAS KANTTUGA', 'Srinivas KATTUNGA'), ('ABHIJEET BHIKAJI PATIL', 'Abhijeet Bhikaji PATIL'), ('SANJAY PARMANAND BATHEJA', 'Sanjay Parmanand BATHEJA'), ('YYOMA DILIP PATHAK', 'Vyoma Dilip PATHAK'), ('ABHIJEET HARISHCHANDRA ALONE', 'Abhijeet Harishchandra ALONE'), ('NASIR AHMED R', 'Nasir Ahmed R')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='reporting_managers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='resource_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RESIGN', 'Resign')], max_length=100, null=True),
        ),
    ]
