# Generated by Django 4.0 on 2022-01-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_employeeuserdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeuserdetails',
            options={'verbose_name_plural': 'EmployeeUserDetails'},
        ),
    ]
